# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master-dotnet-framework ]
  pull_request:
    branches: [ master-dotnet-framework ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    # Setup NuGet
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.5
    
    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore px-dotnet.sln
    
    # Build Solution
    - name: Build Solution
      run: msbuild px-dotnet.sln /p:Configuration=Debug
    
    # Setup VSTest.console.exe
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1
    
    # Run Tests
    - name: Run Tests
      run: |
        ./packages/OpenCover.4.7.922/tools/OpenCover.Console.exe `
        -target:"vstest.console.exe" `
        -targetargs:"MercadoPagoSDK.Test/bin/Debug/MercadoPagoSDK.Test.dll /TestAdapterPath:packages/NUnit3TestAdapter.3.16.1" `
        -filter:"+[*]*MercadoPago.Resources.* -[*]*Disbursement -[*]*DiscountCampaign -[*]*OAuth -[*]*Plan -[*]*Preapproval -[*]*Subscription" `
        -mergebyhash `
        -skipautoprops `
        -register `
        -output:"coverage.xml"
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        EMAIL: ${{ secrets.USER_EMAIL }}

    # Upload coverage result
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
